export const ActionTypes={
    SET_PRODCUTS:'SET_PRODUCTS',
    SELECTED_PRODUCT:'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCTS:'REMOVE_SELECTED_PRODUCTS',
    SET_CAT_PRODUCTS:'SET_CAT_PRODUCTS',
    REMOVE_CAT_PRODUCTS:'REMOVE_CAT_PRODUCTS',
    SET_ALL_CART_PRODUCTS:'SET_ALL_CART_PRODUCTS',
    SET_MAIN_CAT_PRODUCTS:'SET_MAIN_CAT_PRODUCTS',
    REMOVE_MAIN_CAT_PRODUCTS:'REMOVE_MAIN_CAT_PRODUCTS'

}